# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "tank/r/system/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "tank/r/local/nix";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "tank/r/system/var";
      fsType = "zfs";
    };

  fileSystems."/home/hoid" =
    { device = "tank/r/user/home/hoid";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/c775c72e-0762-4b7a-b6b1-06e948228038";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/39e189b9-99bc-4175-9ea5-d0570fa32630"; }
    ];

}
