# bootstrap the plugin manager
evaluate-commands %sh{
  plugins="${kak_config:?}/plugins"
  mkdir -p "$plugins"
  [ ! -e "$plugins/plug.kak" ] && \
    git clone -q https://github.com/andreyorst/plug.kak.git --branch master "$plugins/plug.kak"
  printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}

set-option global plug_always_ensure true
set-option global plug_profile true

# plugins
plug-chain "https://github.com/andreyorst/plug.kak" noload config %{
} plug "https://github.com/alexherbo2/prelude.kak" config %{
} plug "https://github.com/andreyorst/smarttab.kak" defer smarttab %{
  hook global WinSetOption filetype=(rust|kak|sh|nix|c|cpp) expandtab
  set-option global softtabstop 4
} plug "https://github.com/andreyorst/base16-gruvbox.kak" theme config %{
  colorscheme base16-gruvbox-dark-medium
  set-face global CursorLine "default,rgb:303030"
  hook global BufCreate .* %{
    add-highlighter buffer/autowrap_column column '%opt{autowrap_column}' "default,rgb:303030"
  }
} plug "https://gitlab.com/Screwtapello/kakoune-state-save" config %{
} plug "https://github.com/delapouite/kakoune-mirror" config %{
  map global normal "'" ': enter-user-mode -lock mirror<ret>'
} plug "https://github.com/TeddyDD/kakoune-edit-or-dir" config %{
} plug "https://github.com/Delapouite/kakoune-text-objects" config %{
}


# Options
set-option global startup_info_version 20211106
set-option global grepcmd 'rg --no-heading --line-number --column --sort path'
set-option global ui_options terminal_set_title=false terminal_assistant=off
set-option global indentwidth 2
set-option global scrolloff 3,3
set-option global autowrap_fmtcmd 'par -w %c'

# https://github.com/andreyorst/base16-gruvbox.kak/blob/882a612562ddd4a9a4054a1dfee2176fa8846092/colors/base16-gruvbox-dark-hard.kak#L32
declare-option str yellow
declare-option str cyan
declare-option str purple
set-option global yellow "rgb:d79921"
set-option global cyan "rgb:689d6a"
set-option global purple "rgb:b16286"

set-option global modelinefmt '{%opt{yellow}+r} %val{bufname}%opt{modeline_readonly}{{context_info}} {default} '
set-option -add global modelinefmt '{%opt{cyan}}%val{cursor_line}:%val{cursor_char_column}{default} '
set-option -add global modelinefmt '{{mode_info}} '
set-option -add global modelinefmt '{%opt{yellow}}%opt{modeline_filetype}{default}'
set-option -add global modelinefmt '{%opt{purple}+r} %val{client} {default}'
set-option -add global modelinefmt '{%opt{cyan}+r} %val{session} {default}'
set-option -add global modelinefmt '{%opt{yellow}+r} %opt{modeline_position} {default}'

# Highlighters
add-highlighter global/current-line line '%val{cursor_line}' CursorLine

# Commands
source "%val{config}/commands.kak"

# Hooks
source "%val{config}/hooks.kak"

# Keys
source "%val{config}/keys.kak"
