# plug.kak setup
declare-option -docstring "plug.kak's directory" str plugkakdir "%val{config}/plugins/plug.kak"
declare-option -docstring "plug.kak's main script" str plugkak "%opt{plugkakdir}/rc/plug.kak"

try %{
  source "%opt{plugkak}"
} catch %sh{
  if [ ! -d "$kak_opt_plugkakdir" ]; then
    git clone https://github.com/robertmeta/plug.kak.git "$kak_opt_plugkakdir"
    echo 'source "%opt{plugkak}"'
  fi
}

set-option global plug_always_ensure true
set-option global plug_install_dir %sh{ printf %s "${kak_opt_plugkakdir}/../" }

# Plugins
plug "robertmeta/plug.kak" noload
plug "jdugan6240/powerline.kak" config %{
  powerline-start
} defer powerline %{
  powerline-separator global none
}
plug "alexherbo2/prelude.kak" config %{
  require-module prelude
}
plug "alexherbo2/auto-pairs.kak" config %{
  require-module auto-pairs
  hook -once global WinDisplay .* auto-pairs-enable
}
plug "delapouite/kakoune-buffers" config %{
  hook global WinDisplay .* info-buffers
  map global user b ': enter-buffers-mode<ret>' -docstring 'buffers…'
  map global user B ': enter-user-mode -lock buffers<ret>' -docstring 'buffers (lock)…'
}
plug "andreyorst/smarttab.kak" config %{
  hook global WinSetOption filetype=(rust|kak|sh|nix|c|cpp) expandtab
}
plug "dracula/kakoune" theme config %{
  colorscheme dracula-transparent
  face global LineNumberCursor "%opt{yellow}"
  face global MatchingChar "%opt{green}+u"
  face global CursorLine "default,%opt{gray}"
}
plug "Screwtapello/kakoune-state-save" domain "gitlab.com"
plug "fsub/kakoune-mark"
plug "kak-lsp/kak-lsp" do %{
  mkdir -p $HOME/.config/kak-lsp
  [ ! -f $HOME/.config/kak-lsp/kak-lsp.toml ] && cp ./kak-lsp.toml $HOME/.config/kak-lsp
  cargo install --locked --force --path .
}
plug "alexherbo2/view-mode.kak"
plug "delapouite/kakoune-mirror" config %{
  map global normal "'" ': enter-user-mode -lock mirror<ret>'
}

# Options
set-option global startup_info_version 20200901
set-option global grepcmd 'rg --no-heading --line-number --column --sort path'
set-option global ui_options ncurses_set_title=false ncurses_assistant=off
set-option global indentwidth 2
set-option global scrolloff 3,3
set-option global autowrap_fmtcmd 'par -w %c'

# Highlighters
add-highlighter global/show-trailing-whitespace regex '\h+$' 0:Error
add-highlighter global/current-line line '%val{cursor_line}' CursorLine

# Commands
source "%val{config}/commands.kak"

# Hooks
source "%val{config}/hooks.kak"

# Keys
source "%val{config}/keys.kak"
