# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@iarna/toml-2.2.5" = {
      name = "_at_iarna_slash_toml";
      packageName = "@iarna/toml";
      version = "2.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@iarna/toml/-/toml-2.2.5.tgz";
        sha512 = "trnsAYxU3xnS1gPHPyU961coFyLkh4gAD/0zQ5mymY4yOZ+CYvsPqUbOFSw0aDM4y0tV7tiFxL/1XfXPNC6IPg==";
      };
    };
    "@ot-builder/bin-composite-types-1.0.1" = {
      name = "_at_ot-builder_slash_bin-composite-types";
      packageName = "@ot-builder/bin-composite-types";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/bin-composite-types/-/bin-composite-types-1.0.1.tgz";
        sha512 = "OwX0d7IN7LhgeWiPPftMTcGYVisMPWXuvuLQHdc7gO+1Sg/7+XbMwXbdYI1PvJwqNlqKPE5+yVesjgVtt1RRwQ==";
      };
    };
    "@ot-builder/bin-util-1.0.1" = {
      name = "_at_ot-builder_slash_bin-util";
      packageName = "@ot-builder/bin-util";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/bin-util/-/bin-util-1.0.1.tgz";
        sha512 = "LN6iR+Y/gmRkRoxW6VV5U1SIDRu9zQ5ZshePQukp1+gdJQJBrhmCrreL4XEEOQ/3AC67yuj6pAPi70jagqKxyA==";
      };
    };
    "@ot-builder/cli-help-shower-1.0.1" = {
      name = "_at_ot-builder_slash_cli-help-shower";
      packageName = "@ot-builder/cli-help-shower";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/cli-help-shower/-/cli-help-shower-1.0.1.tgz";
        sha512 = "oCsKX1ecjd1L8uOmU1z0YziizRoOWN4NOhnDU+sLGtPYPnM9bOzKprfY6W99NFkTYu27N19glwFUPM/s0F+nNA==";
      };
    };
    "@ot-builder/cli-proc-1.0.1" = {
      name = "_at_ot-builder_slash_cli-proc";
      packageName = "@ot-builder/cli-proc";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/cli-proc/-/cli-proc-1.0.1.tgz";
        sha512 = "lR90Mb/Wmm2GZH0tBIGjfZhh/VxQl5YiwXVjQIo7UM5iFviHf44lYqVkn0vyE9D1IT5E/tA1OzDrjpIBG7WBKQ==";
      };
    };
    "@ot-builder/cli-shared-1.0.1" = {
      name = "_at_ot-builder_slash_cli-shared";
      packageName = "@ot-builder/cli-shared";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/cli-shared/-/cli-shared-1.0.1.tgz";
        sha512 = "I9Zd7gRiZdD+MFr13A9zH2CRvEkjZX91OfkDiAxpDM9ncKlnlZpbbIVp3nh0VCbUAad9lrdc+xI+MMwOEPKhIA==";
      };
    };
    "@ot-builder/common-impl-1.0.1" = {
      name = "_at_ot-builder_slash_common-impl";
      packageName = "@ot-builder/common-impl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/common-impl/-/common-impl-1.0.1.tgz";
        sha512 = "v0r2tPYO8MTmx6Eo6cPGCXYZe2ScX4zA9xAfqvXn//h0sr4K11k3F6ELLDY64zKASOhITcWgznU3Prt3ubpkjg==";
      };
    };
    "@ot-builder/errors-1.0.1" = {
      name = "_at_ot-builder_slash_errors";
      packageName = "@ot-builder/errors";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/errors/-/errors-1.0.1.tgz";
        sha512 = "66pRCyZq/uESMHTb6Wz3FYwUr6YYnuJ+sJMGyfvOCCvwZzlUYiZZ9r0lPjh/lvZ3j1UYFG6OvpIgUeBCqean9w==";
      };
    };
    "@ot-builder/io-bin-cff-1.0.1" = {
      name = "_at_ot-builder_slash_io-bin-cff";
      packageName = "@ot-builder/io-bin-cff";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-cff/-/io-bin-cff-1.0.1.tgz";
        sha512 = "rEuNFXtyU0/a2xpqTHajIZ8YgEkVdB7XImODrs308zlkHdaWL6akOUgBNr866qj6kVWEdfnXkcF0ZCaRJYrCzA==";
      };
    };
    "@ot-builder/io-bin-encoding-1.0.1" = {
      name = "_at_ot-builder_slash_io-bin-encoding";
      packageName = "@ot-builder/io-bin-encoding";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-encoding/-/io-bin-encoding-1.0.1.tgz";
        sha512 = "50IRjuNn2vJny5QXFcEp7EccfHEVZ8TTp4TdA6w6pyNtqxyUSHukrqJTpnO30jitNS+NRSqdoI9EHDgZh2Z5IQ==";
      };
    };
    "@ot-builder/io-bin-ext-private-1.0.1" = {
      name = "_at_ot-builder_slash_io-bin-ext-private";
      packageName = "@ot-builder/io-bin-ext-private";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-ext-private/-/io-bin-ext-private-1.0.1.tgz";
        sha512 = "+vWNtsB9YDoM6bYcADfQEw5g9BIM1qbNlYDtntas/3BcEkjtMC2hUmHfkjPYJCaLpJSROUTqH9n+3Ih+OLgvRw==";
      };
    };
    "@ot-builder/io-bin-font-1.0.1" = {
      name = "_at_ot-builder_slash_io-bin-font";
      packageName = "@ot-builder/io-bin-font";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-font/-/io-bin-font-1.0.1.tgz";
        sha512 = "GQ605nx70kUD3Mu+4RZ7+GyO5Yp6zGG4+Lrw6Fpmyd7aCTchCeYkHAIAuIUtzkTo/xKTg+MDQqHUK1a9V9hQpw==";
      };
    };
    "@ot-builder/io-bin-glyph-store-1.0.1" = {
      name = "_at_ot-builder_slash_io-bin-glyph-store";
      packageName = "@ot-builder/io-bin-glyph-store";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-glyph-store/-/io-bin-glyph-store-1.0.1.tgz";
        sha512 = "O51k7dReVjls62SfpIh+bNv053dxqRq+fbHBwU2mXo/klKk+T7NIQvaWqZpomUFlY3nrNv9AOAlAHZzjkHyIeA==";
      };
    };
    "@ot-builder/io-bin-layout-1.0.1" = {
      name = "_at_ot-builder_slash_io-bin-layout";
      packageName = "@ot-builder/io-bin-layout";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-layout/-/io-bin-layout-1.0.1.tgz";
        sha512 = "dfdqHp77r5jixq0E/7v/PyrMWVKVtZPCEAa7QonPIfFxoG5a/nq9hzuXSLldg8GxuUXzEqV3waXB9sSo7KpOCg==";
      };
    };
    "@ot-builder/io-bin-metadata-1.0.1" = {
      name = "_at_ot-builder_slash_io-bin-metadata";
      packageName = "@ot-builder/io-bin-metadata";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-metadata/-/io-bin-metadata-1.0.1.tgz";
        sha512 = "c5DMb048oMO3WKkeszVif5OVN1ZCEGexBjPBS06zIeRB3F0X+/ZjCjbtx6WWXRvF9DkZDrDMAFDmG3dAhtPvdA==";
      };
    };
    "@ot-builder/io-bin-metric-1.0.1" = {
      name = "_at_ot-builder_slash_io-bin-metric";
      packageName = "@ot-builder/io-bin-metric";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-metric/-/io-bin-metric-1.0.1.tgz";
        sha512 = "vRodhi6NOZ3J91XtnhNRC/i4FyUhV4xFA3kavsJvuRa6kmubSmkqoH1xYGgIxvRxi3pRdfojGI9+a/usZ5DikA==";
      };
    };
    "@ot-builder/io-bin-name-1.0.1" = {
      name = "_at_ot-builder_slash_io-bin-name";
      packageName = "@ot-builder/io-bin-name";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-name/-/io-bin-name-1.0.1.tgz";
        sha512 = "GnOPDSjIFG2uR2tbEondXqEt2ArISyTn7yXJbYM3AG4hdY52xn/mFcEvidgHEYLDDOkxuxoNTBDnbeCg3LxEyA==";
      };
    };
    "@ot-builder/io-bin-sfnt-1.0.1" = {
      name = "_at_ot-builder_slash_io-bin-sfnt";
      packageName = "@ot-builder/io-bin-sfnt";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-sfnt/-/io-bin-sfnt-1.0.1.tgz";
        sha512 = "5TjEG3bEthvgn/LlQT/c2wSiPUeY+7jmfPr6+7G839avl/31FwxYIbhCjrjWbg/ceuo8NNRxvmi7H+m1HwjcBg==";
      };
    };
    "@ot-builder/io-bin-ttf-1.0.1" = {
      name = "_at_ot-builder_slash_io-bin-ttf";
      packageName = "@ot-builder/io-bin-ttf";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-ttf/-/io-bin-ttf-1.0.1.tgz";
        sha512 = "nYRGtMLRDZdrSkCxp6sDjFeSeOEsCDTMFWBZrNSeRKINSvDmXpVJQCKLqx+TBZBykNb9Cf7+iCuNG5YfNUiEGg==";
      };
    };
    "@ot-builder/ot-1.0.1" = {
      name = "_at_ot-builder_slash_ot";
      packageName = "@ot-builder/ot";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot/-/ot-1.0.1.tgz";
        sha512 = "l+nQjrTWO6De0OkX1ETC+7Pr8gArJL5L+2vhYdktiqe0tAC/odmu/dVINMenqOufC+DVzJLHhCyFNT/HrukGCA==";
      };
    };
    "@ot-builder/ot-encoding-1.0.1" = {
      name = "_at_ot-builder_slash_ot-encoding";
      packageName = "@ot-builder/ot-encoding";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot-encoding/-/ot-encoding-1.0.1.tgz";
        sha512 = "eY1L/Waa9J7OAu5xaggvied4qKnJobpfELVcrDTdsR85F7JJQMdV2P1o9oRS0tzf6nHMfhkCihV5IlLqLxS1eQ==";
      };
    };
    "@ot-builder/ot-ext-private-1.0.1" = {
      name = "_at_ot-builder_slash_ot-ext-private";
      packageName = "@ot-builder/ot-ext-private";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot-ext-private/-/ot-ext-private-1.0.1.tgz";
        sha512 = "VTagNcyvtC9EmfVHDAni78dYX97k+Hd1/ruDRSPAJhttLA5xiLWah9xAuPeQtBcglFx7375N8qA9f6CQgFBrBA==";
      };
    };
    "@ot-builder/ot-glyphs-1.0.1" = {
      name = "_at_ot-builder_slash_ot-glyphs";
      packageName = "@ot-builder/ot-glyphs";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot-glyphs/-/ot-glyphs-1.0.1.tgz";
        sha512 = "FZfcl61XFO393QOBZK8hzRAdavVHW5tUKEzkZzlnDWJEhlZNUTqycn+nJWc5rwfMtQnnJ4UQ1DdJDUTaDZ2VHQ==";
      };
    };
    "@ot-builder/ot-layout-1.0.1" = {
      name = "_at_ot-builder_slash_ot-layout";
      packageName = "@ot-builder/ot-layout";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot-layout/-/ot-layout-1.0.1.tgz";
        sha512 = "1Kes3RWBnP+k6bCtQAASquh4zDHvJI7BcD+vS0FyerwvniarxGxw4CELmLN87xGrQBybmez/aftqXnRmhsjrRQ==";
      };
    };
    "@ot-builder/ot-metadata-1.0.1" = {
      name = "_at_ot-builder_slash_ot-metadata";
      packageName = "@ot-builder/ot-metadata";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot-metadata/-/ot-metadata-1.0.1.tgz";
        sha512 = "YO6WGvXyhvSCmsGdkK/L37YzoMpFn6A8YoDgMJk4R0MPjoJuVta4srDv41RvOLVr9oDiYtiPFRw8BjkdEWrMbg==";
      };
    };
    "@ot-builder/ot-name-1.0.1" = {
      name = "_at_ot-builder_slash_ot-name";
      packageName = "@ot-builder/ot-name";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot-name/-/ot-name-1.0.1.tgz";
        sha512 = "6L4SAwLALNOjifhX47HvXPkGKcX1HfpeGnzFtMDtgUi3muiYrKb3YJffV8vk8V1EQhiVTWJ1j7441SS6cY2m8g==";
      };
    };
    "@ot-builder/ot-sfnt-1.0.1" = {
      name = "_at_ot-builder_slash_ot-sfnt";
      packageName = "@ot-builder/ot-sfnt";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot-sfnt/-/ot-sfnt-1.0.1.tgz";
        sha512 = "jmojZ36QbcDUIXX+UPYlKtkxklKSlV35Cpa4P4vWVAISqocmX3fFIQ+Xz7Ub1XeLnkcIf86ruOrDyoSytF5NHg==";
      };
    };
    "@ot-builder/ot-standard-glyph-namer-1.0.1" = {
      name = "_at_ot-builder_slash_ot-standard-glyph-namer";
      packageName = "@ot-builder/ot-standard-glyph-namer";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot-standard-glyph-namer/-/ot-standard-glyph-namer-1.0.1.tgz";
        sha512 = "yKgPw8neJZr/wa/mFWtPbi4sKTkfyYCo+Q0SONkjJLNchuI6i/w3ijX3EDf8R9/m4j65JhHKQ8wltKBnRgHlCQ==";
      };
    };
    "@ot-builder/prelude-1.0.1" = {
      name = "_at_ot-builder_slash_prelude";
      packageName = "@ot-builder/prelude";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/prelude/-/prelude-1.0.1.tgz";
        sha512 = "ocaoVx+QeYm5aYjzy+gD67cK1j/JGArqTjGXmo/ndjsBCvS9Ni9QpN4UEjoN2oz8rzr0sK4RhX9fJ7ufQ27gPA==";
      };
    };
    "@ot-builder/primitive-1.0.1" = {
      name = "_at_ot-builder_slash_primitive";
      packageName = "@ot-builder/primitive";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/primitive/-/primitive-1.0.1.tgz";
        sha512 = "mRSNfNNf7qUmZJ23UJVK6VnITRKgGQC5X1I1DFlIve/YfTVe6SbH0AbBBcS4OsC/gXskLkywXX6rZChjSWDmTg==";
      };
    };
    "@ot-builder/rectify-1.0.1" = {
      name = "_at_ot-builder_slash_rectify";
      packageName = "@ot-builder/rectify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/rectify/-/rectify-1.0.1.tgz";
        sha512 = "IBA/v+6ksxUADQEpk1Nbc0jRwXhZD2CNPz8xmtPPqnRAE3b8JpxIjmu6zhn1pRx0E0AvtPdMfAilhNis7IzY9g==";
      };
    };
    "@ot-builder/stat-glyphs-1.0.1" = {
      name = "_at_ot-builder_slash_stat-glyphs";
      packageName = "@ot-builder/stat-glyphs";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/stat-glyphs/-/stat-glyphs-1.0.1.tgz";
        sha512 = "YgsglcyhfAHNpbPXdPoZD4DhqbaHzAhtocJ/cblaOQr+uE7LD66890is1kJ4mrKUYV4Ei0uLZDyw9ngixZGteg==";
      };
    };
    "@ot-builder/trace-1.0.1" = {
      name = "_at_ot-builder_slash_trace";
      packageName = "@ot-builder/trace";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/trace/-/trace-1.0.1.tgz";
        sha512 = "UZ7Fi+A+LEnkjagFeCiPlzFKSrBtY04l/B2iXqlC4gyfmwOzKGe+A8B0kVfjheePhteUm4808Yx3e419o2EepQ==";
      };
    };
    "@ot-builder/var-store-1.0.1" = {
      name = "_at_ot-builder_slash_var-store";
      packageName = "@ot-builder/var-store";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/var-store/-/var-store-1.0.1.tgz";
        sha512 = "IcoJ7U+Z+wjbFSL2qLuU0tIW9G/NR6sWI0r1bKgnBr0hE2Si4dj/D+GYjIVkRscfvI3x/5/XL2sWayuh2Pjvdg==";
      };
    };
    "@ot-builder/variance-1.0.1" = {
      name = "_at_ot-builder_slash_variance";
      packageName = "@ot-builder/variance";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/variance/-/variance-1.0.1.tgz";
        sha512 = "cJ4eL1xyvJnPlEcrnKkZeqIw6NbPGAP2RFyEclBU2U4Freu2ZH1R8WqATbekdQqlOnwoZ1vgV8mH8EpNI3N8Uw==";
      };
    };
    "@unicode/unicode-13.0.0-1.0.3" = {
      name = "_at_unicode_slash_unicode-13.0.0";
      packageName = "@unicode/unicode-13.0.0";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unicode/unicode-13.0.0/-/unicode-13.0.0-1.0.3.tgz";
        sha512 = "foNhrvnwzUpt6Od/L7hgkNwZkDjsGMPgPFdVcXSdcKKYNicNBySiypBwgLLMsdBLWS30aJ8eLjftifnGuNGN1g==";
      };
    };
    "amdefine-1.0.1" = {
      name = "amdefine";
      packageName = "amdefine";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz";
        sha1 = "4a5282ac164729e93619bcfd3ad151f817ce91f5";
      };
    };
    "ansi-regex-5.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.0.tgz";
        sha512 = "bY6fj56OUQ0hU1KjFNDQuJFezqKdrAyFdIevADiqrWHwSlbmBNMHp5ak2f40Pm8JTFyM2mqxkG6ngkHO11f/lg==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "async-0.9.2" = {
      name = "async";
      packageName = "async";
      version = "0.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.9.2.tgz";
        sha1 = "aea74d5e61c1f899613bf64bda66d4c78f2fd17d";
      };
    };
    "at-least-node-1.0.0" = {
      name = "at-least-node";
      packageName = "at-least-node";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/at-least-node/-/at-least-node-1.0.0.tgz";
        sha512 = "+q/t7Ekv1EDY2l6Gda6LLiX14rU9TV20Wa3ofeQmwPFZbOMo9DXrLbOjFaaclkXKWidIaopwAObQDqwWtGUjqg==";
      };
    };
    "atob-2.1.2" = {
      name = "atob";
      packageName = "atob";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/atob/-/atob-2.1.2.tgz";
        sha512 = "Wm6ukoaOGJi/73p/cl2GvLjTI5JM1k/O14isD73YML8StrH/7/lRFgmg8nICZgD3bZZvjwCGxtMOD3wWNAu8cg==";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "bluebird-3.7.2" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.7.2.tgz";
        sha512 = "XpNj6GDQzdfW+r2Wnn7xiSAd7TM3jzkxGXBGTtWKuSXv1xUV+azxAm8jdWZN06QTQk+2N2XB9jRDkvbmQmcRtg==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "camelcase-5.3.1" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "5.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-5.3.1.tgz";
        sha512 = "L28STB170nwWS63UjtlEOE3dldQApaJXZkOI1uMFfzf3rRuPegHaHesyee+YxQ+W6SvRDQV6UrdOdRiR153wJg==";
      };
    };
    "chainsaw-0.0.9" = {
      name = "chainsaw";
      packageName = "chainsaw";
      version = "0.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/chainsaw/-/chainsaw-0.0.9.tgz";
        sha1 = "11a05102d1c4c785b6d0415d336d5a3a1612913e";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "chalk-4.1.0" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.0.tgz";
        sha512 = "qwx12AxXe2Q5xQ43Ac//I6v5aXTipYrSESdOgzrN+9XjgEpyjpKuvSGaN4qE93f7TQTlerQQ8S+EQ0EyDoVL1A==";
      };
    };
    "cldr-5.8.0" = {
      name = "cldr";
      packageName = "cldr";
      version = "5.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cldr/-/cldr-5.8.0.tgz";
        sha512 = "w0L5FX4X3txDX5G/YSbDAQuneVSFPSKjOXB2ehWh/J6BN7RJ+IUEVNG9hIGjuJoyYJcVGE2AoL0W0VSjirQPIg==";
      };
    };
    "cli-cursor-3.1.0" = {
      name = "cli-cursor";
      packageName = "cli-cursor";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-cursor/-/cli-cursor-3.1.0.tgz";
        sha512 = "I/zHAwsKf9FqGoXM4WWRACob9+SNukZTd94DWF57E4toouRulbCxcUh6RKUEOQlYTHJnzkPMySvPNaaSLNfLZw==";
      };
    };
    "clipper-lib-6.4.2" = {
      name = "clipper-lib";
      packageName = "clipper-lib";
      version = "6.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clipper-lib/-/clipper-lib-6.4.2.tgz";
        sha512 = "knglhjQX5ihNj/XCIs6zCHrTemdvHY3LPZP9XB2nq2/3igyYMFueFXtfp84baJvEE+f8pO1ZS4UVeEgmLnAprQ==";
      };
    };
    "cliui-6.0.0" = {
      name = "cliui";
      packageName = "cliui";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-6.0.0.tgz";
        sha512 = "t6wbgtoCXvAzst7QgXxJYqPt0usEfbgQdftEPbLL/cvv6HPE5VgvqCuAIDR0NgU52ds6rFwqrgakNLrHEjCbrQ==";
      };
    };
    "cliui-7.0.4" = {
      name = "cliui";
      packageName = "cliui";
      version = "7.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-7.0.4.tgz";
        sha512 = "OcRE68cOsVMXp1Yvonl/fzkQOyjLSu/8bhPDfQt0e0/Eb283TKP20Fs2MqoPsr9SwA595rRCA+QMzYc9nBP+JQ==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "css-2.2.4" = {
      name = "css";
      packageName = "css";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/css/-/css-2.2.4.tgz";
        sha512 = "oUnjmWpy0niI3x/mPL8dVEI1l7MnG3+HHyRPHf+YFSbK+svOhXpmSOcDURUh2aOCgl2grzrOPt1nHLuCVFULLw==";
      };
    };
    "css-parse-2.0.0" = {
      name = "css-parse";
      packageName = "css-parse";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-parse/-/css-parse-2.0.0.tgz";
        sha1 = "a468ee667c16d81ccf05c58c38d2a97c780dbfd4";
      };
    };
    "debug-3.1.0" = {
      name = "debug";
      packageName = "debug";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz";
        sha512 = "OX8XqP7/1a9cqkxYw2yXss15f26NKWBpDXQd0/uK/KPqdQhxbPa994hnzjcE2VqQpDslf55723cKPUOGSmMY3g==";
      };
    };
    "decamelize-1.2.0" = {
      name = "decamelize";
      packageName = "decamelize";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
        sha1 = "f6534d15148269b20352e7bee26f501f9a191290";
      };
    };
    "decode-uri-component-0.2.0" = {
      name = "decode-uri-component";
      packageName = "decode-uri-component";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decode-uri-component/-/decode-uri-component-0.2.0.tgz";
        sha1 = "eb3913333458775cb84cd1a1fae062106bb87545";
      };
    };
    "deep-is-0.1.3" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.3.tgz";
        sha1 = "b369d6fb5dbc13eecf524f91b070feedc357cf34";
      };
    };
    "ejs-3.1.6" = {
      name = "ejs";
      packageName = "ejs";
      version = "3.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ejs/-/ejs-3.1.6.tgz";
        sha512 = "9lt9Zse4hPucPkoP7FHDF0LQAlGyF9JVpnClFLFH3aSSbxmyoqINRpp/9wePWJTUl4KOQwRL72Iw3InHPDkoGw==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "escalade-3.1.1" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.1.tgz";
        sha512 = "k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "escodegen-1.3.3" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-1.3.3.tgz";
        sha1 = "f024016f5a88e046fd12005055e939802e6c5f23";
      };
    };
    "escodegen-2.0.0" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-2.0.0.tgz";
        sha512 = "mmHKys/C8BFUGI+MAWNcSYoORYLMdPzjrknd2Vc+bUsjN5bXcr8EhrNB+UTqfL1y3I9c4fw2ihgtMPQLBRiQxw==";
      };
    };
    "escope-1.0.3" = {
      name = "escope";
      packageName = "escope";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escope/-/escope-1.0.3.tgz";
        sha1 = "759dce8496c4248fec2d0caaf4108bcf3f1a7f5d";
      };
    };
    "esmangle-1.0.1" = {
      name = "esmangle";
      packageName = "esmangle";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esmangle/-/esmangle-1.0.1.tgz";
        sha1 = "d9bb37b8f8eafbf4e6d4ed6b7aa2956abbd3c4c2";
      };
    };
    "esprima-1.1.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-1.1.1.tgz";
        sha1 = "5b6f1547f4d102e670e140c509be6771d6aeb549";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "esshorten-1.1.1" = {
      name = "esshorten";
      packageName = "esshorten";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esshorten/-/esshorten-1.1.1.tgz";
        sha1 = "174f96b7cc267e46872d814e7db7c290bdff61a9";
      };
    };
    "estraverse-1.5.1" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-1.5.1.tgz";
        sha1 = "867a3e8e58a9f84618afb6c2ddbcd916b7cbaf71";
      };
    };
    "estraverse-2.0.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-2.0.0.tgz";
        sha1 = "5ae46963243600206674ccb24a09e16674fcdca1";
      };
    };
    "estraverse-4.1.1" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.1.1.tgz";
        sha1 = "f6caca728933a850ef90661d0e17982ba47111a2";
      };
    };
    "estraverse-5.2.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-5.2.0.tgz";
        sha512 = "BxbNGGNm0RyRYvUdHpIwv9IWzeM9XClbOxwoATuFdOE7ZE6wHL+HQ5T8hoPM+zHvmKzzsEqhgy0GrQ5X13afiQ==";
      };
    };
    "esutils-1.0.0" = {
      name = "esutils";
      packageName = "esutils";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-1.0.0.tgz";
        sha1 = "8151d358e20c8acc7fb745e7472c0025fe496570";
      };
    };
    "esutils-2.0.3" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.3.tgz";
        sha512 = "kVscqXk4OCp68SZ0dkgEKVi6/8ij300KBWTJq32P/dYeWTSwK41WyTxalN1eRmA5Z9UU/LX9D7FWSmV9SAYx6g==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fast-levenshtein-1.0.7" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-1.0.7.tgz";
        sha1 = "0178dcdee023b92905193af0959e8a7639cfdcb9";
      };
    };
    "fast-levenshtein-2.0.6" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz";
        sha1 = "3d8a5c66883a16a30ca8643e851f19baa7797917";
      };
    };
    "filelist-1.0.2" = {
      name = "filelist";
      packageName = "filelist";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/filelist/-/filelist-1.0.2.tgz";
        sha512 = "z7O0IS8Plc39rTCq6i6iHxk43duYOn8uFJiWSewIq0Bww1RNybVHSCjahmcC87ZqAm4OTvFzlzeGu3XAzG1ctQ==";
      };
    };
    "find-up-4.1.0" = {
      name = "find-up";
      packageName = "find-up";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-4.1.0.tgz";
        sha512 = "PpOwAdQ/YlXQ2vj8a3h8IipDuYRi3wceVQQGYWxNINccq40Anw7BlsEXCMbt1Zt+OLA6Fq9suIpIWD0OsnISlw==";
      };
    };
    "fs-extra-9.1.0" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "9.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-9.1.0.tgz";
        sha512 = "hcg3ZmepS30/7BSFqRvoo3DOMQu7IjqxO5nCDt+zM9XWjb33Wg7ziNT+Qvqbuc3+gWpzO02JubVyk2G4Zvo1OQ==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "get-caller-file-2.0.5" = {
      name = "get-caller-file";
      packageName = "get-caller-file";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-2.0.5.tgz";
        sha512 = "DyFP3BM/3YHTQOCUL/w0OZHR0lpKeGrxotcHWcqNEdnltqFwXVfhEBQ94eIo34AfQpo0rGki4cyIiftY06h2Fg==";
      };
    };
    "glob-7.1.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.6.tgz";
        sha512 = "LwaxwyZ72Lk7vZINtNNrywX0ZuLyStrdDtabefZKAY5ZGJhVtgdznluResxNmPitE0SAO+O26sWTHeKSI2wMBA==";
      };
    };
    "graceful-fs-4.2.5" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.5.tgz";
        sha512 = "kBBSQbz2K0Nyn+31j/w36fUfxkBW9/gfwRWdUY1ULReH3iokVJgddZAFcD1D0xlgTmFxJCbUkUclAlc6/IDJkw==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "hashish-0.0.4" = {
      name = "hashish";
      packageName = "hashish";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/hashish/-/hashish-0.0.4.tgz";
        sha1 = "6d60bc6ffaf711b6afd60e426d077988014e6554";
      };
    };
    "iconv-lite-0.6.2" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.2.tgz";
        sha512 = "2y91h5OpQlolefMPmUlivelittSWy0rP+oYVpn6A7GwVHNE8AWzoYOBNmlwks3LobaJxgHCYZAnyNo2GgpNRNQ==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-core-module-2.2.0" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.2.0.tgz";
        sha512 = "XRAfAdyyY5F5cOXn7hYQDqh2Xmii+DEfIcQGxK/uNwMHhIkPWO0g8msXcbzLe+MpGoR951MlqM/2iIlU4vKDdQ==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "jake-10.8.2" = {
      name = "jake";
      packageName = "jake";
      version = "10.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jake/-/jake-10.8.2.tgz";
        sha512 = "eLpKyrfG3mzvGE2Du8VoPbeSkRry093+tyNjdYaBbJS9v17knImYGNXQCUV0gLxQtF82m3E8iRb/wdSQZLoq7A==";
      };
    };
    "jsonfile-6.1.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-6.1.0.tgz";
        sha512 = "5dgndWOriYSm5cnYaJNhalLNDKOqFwyDB/rr1E9ZsGciGvKPs8R2xYGCacuf3z6K1YKDz182fd+fY3cn3pMqXQ==";
      };
    };
    "levn-0.2.5" = {
      name = "levn";
      packageName = "levn";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.2.5.tgz";
        sha1 = "ba8d339d0ca4a610e3a3f145b9caf48807155054";
      };
    };
    "levn-0.3.0" = {
      name = "levn";
      packageName = "levn";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.3.0.tgz";
        sha1 = "3b09924edf9f083c0490fdd4c0bc4421e04764ee";
      };
    };
    "locate-path-5.0.0" = {
      name = "locate-path";
      packageName = "locate-path";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-path/-/locate-path-5.0.0.tgz";
        sha512 = "t7hw9pI+WvuwNJXwk5zVHpyhIqzg2qTlklJOf0mVxGSbe3Fp2VieZcduNYjaLDoy6p9uGpQEGWG87WpMKlNq8g==";
      };
    };
    "lru-cache-2.5.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-2.5.0.tgz";
        sha1 = "d82388ae9c960becbea0c73bb9eb79b6c6ce9aeb";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "memoizeasync-1.1.0" = {
      name = "memoizeasync";
      packageName = "memoizeasync";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/memoizeasync/-/memoizeasync-1.1.0.tgz";
        sha1 = "9d7028a6f266deb733510bb7dbba5f51878c561e";
      };
    };
    "mimic-fn-2.1.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz";
        sha512 = "OqbOk5oEQeAZ8WXWydlu9HJjz9WVdEIvamMCcXmuqUYjTknH/sqsWvhQ3vgwKFRR1HpjvNBKQ37nbJgYzGqGcg==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "mkdirp-1.0.4" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz";
        sha512 = "vVqVZQyf3WLx2Shd0qJ9xuvqgAyKPLAiqITEtqW0oIUjzo3PePDd6fW9iFz30ef7Ysp/oiWqbhszeGWW2T6Gzw==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "onetime-5.1.2" = {
      name = "onetime";
      packageName = "onetime";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-5.1.2.tgz";
        sha512 = "kbpaSSGJTWdAY5KPVeMOKXSrPtr8C8C7wodJbcsd51jRnmD+GZu8Y0VoU6Dm5Z4vWr0Ig/1NKuWRKf7j5aaYSg==";
      };
    };
    "optionator-0.3.0" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.3.0.tgz";
        sha1 = "9715a8b5f5e7586cff06c8249e039cd7364d3f54";
      };
    };
    "optionator-0.8.3" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.8.3.tgz";
        sha512 = "+IW9pACdk3XWmmTXG8m3upGUJst5XRGzxMRjXzAuJ1XnIFNvfhjjIuYkDvysnPQ7qzqVzLt78BCruntqRhWQbA==";
      };
    };
    "ot-builder-1.0.1" = {
      name = "ot-builder";
      packageName = "ot-builder";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ot-builder/-/ot-builder-1.0.1.tgz";
        sha512 = "tx0ZlR8KGohvVketGtOmd5nClqvdoWPxMwugihnkzSu2z75b1uAgEfiJ2gvZLix+re20trKq/HooYv+iQ+kmjA==";
      };
    };
    "otb-ttc-bundle-1.0.1" = {
      name = "otb-ttc-bundle";
      packageName = "otb-ttc-bundle";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/otb-ttc-bundle/-/otb-ttc-bundle-1.0.1.tgz";
        sha512 = "dkdU3V3jqOLOSABpKYzl1mocygPZUhv6DjJSip5Hp2L7PVsDKv1xS+TNf+SQSBlPYPXLzP6cwvbDvwsqeeCEBw==";
      };
    };
    "p-limit-2.3.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-2.3.0.tgz";
        sha512 = "//88mFWSJx8lxCzwdAABTJL2MyWB12+eIY7MDL2SqLmAkeKU9qxRvWuSyTjm3FUmpBEMuFfckAIqEaVGUDxb6w==";
      };
    };
    "p-locate-4.1.0" = {
      name = "p-locate";
      packageName = "p-locate";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-locate/-/p-locate-4.1.0.tgz";
        sha512 = "R79ZZ/0wAxKGu3oYMlz8jy/kbhsNrS7SKZ7PxEHBgJ5+F2mtFW2fK2cOtBh1cHYkQsbzFV7I+EoRKe6Yt0oK7A==";
      };
    };
    "p-try-2.2.0" = {
      name = "p-try";
      packageName = "p-try";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-try/-/p-try-2.2.0.tgz";
        sha512 = "R4nPAVTAU0B9D35/Gk3uJf/7XYbQcyohSKdvAxIRSNghFl4e71hVoGnBNQz9cWaXxO2I10KTC+3jMdvvoKw6dQ==";
      };
    };
    "passerror-1.1.1" = {
      name = "passerror";
      packageName = "passerror";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/passerror/-/passerror-1.1.1.tgz";
        sha1 = "a25b88dbdd910a29603aec7dcb96e9a7a97687b4";
      };
    };
    "patel-0.34.0" = {
      name = "patel";
      packageName = "patel";
      version = "0.34.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/patel/-/patel-0.34.0.tgz";
        sha512 = "3EvIzxbIFknpPa9QL2LYW+B35qFwER3Dn674KSC9Hc7DIuLJ7YMUJOR4dvCMPmpj/lB4fDvfr/VYV7FKKLEpFA==";
      };
    };
    "path-exists-4.0.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-4.0.0.tgz";
        sha512 = "ak9Qy5Q7jYb2Wwcey5Fpvg2KoAc/ZIhLSLOSBmRmygPsGwkVVt0fZa0qrtMz+m6tJTAHfZQ8FnmB4MG4LWy7/w==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-parse-1.0.6" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.6.tgz";
        sha512 = "GSmOT2EbHrINBf9SR7CDELwlJ8AENk3Qn7OikK4nFYAu3Ote2+JYNVvkpAEQm3/TLNEJFD/xZJjzyxg3KBWOzw==";
      };
    };
    "patrisika-0.22.2" = {
      name = "patrisika";
      packageName = "patrisika";
      version = "0.22.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/patrisika/-/patrisika-0.22.2.tgz";
        sha512 = "8L6zlp+F4InnoFv0jjGdar948yEzP30bE96f6RHnECaUsU9BWRiTBhkAuhIobG4Lrr8CBscUcar7UWe0Bm1lqA==";
      };
    };
    "patrisika-scopes-0.11.1" = {
      name = "patrisika-scopes";
      packageName = "patrisika-scopes";
      version = "0.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/patrisika-scopes/-/patrisika-scopes-0.11.1.tgz";
        sha512 = "UCIBMx1nzNaR5CcDoQ9/jtY5RlJqf2CrJYHiMZJhi15NPvsPKRfJT/DPZMkhCunexOKmH03EDZYZU1hGn7mL0w==";
      };
    };
    "pegjs-0.10.0" = {
      name = "pegjs";
      packageName = "pegjs";
      version = "0.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pegjs/-/pegjs-0.10.0.tgz";
        sha1 = "cf8bafae6eddff4b5a7efb185269eaaf4610ddbd";
      };
    };
    "prelude-ls-1.1.2" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz";
        sha1 = "21932a549f5e52ffd9a827f570e04be62a97da54";
      };
    };
    "require-directory-2.1.1" = {
      name = "require-directory";
      packageName = "require-directory";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz";
        sha1 = "8c64ad5fd30dab1c976e2344ffe7f792a6a6df42";
      };
    };
    "require-main-filename-2.0.0" = {
      name = "require-main-filename";
      packageName = "require-main-filename";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-main-filename/-/require-main-filename-2.0.0.tgz";
        sha512 = "NKN5kMDylKuldxYLSUfrbo5Tuzh4hd+2E8NPPX02mZtn1VuREQToYe/ZdlJy+J3uCpfaiGF05e7B8W0iXbQHmg==";
      };
    };
    "resolve-1.19.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.19.0.tgz";
        sha512 = "rArEXAgsBG4UgRGcynxWIWKFvh/XZCcS8UJdHhwy91zwAvCZIbcs+vAbflgBnNjYMs/i/i+/Ux6IZhML1yPvxg==";
      };
    };
    "resolve-url-0.2.1" = {
      name = "resolve-url";
      packageName = "resolve-url";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-url/-/resolve-url-0.2.1.tgz";
        sha1 = "2c637fe77c893afd2a663fe21aa9080068e2052a";
      };
    };
    "restore-cursor-3.1.0" = {
      name = "restore-cursor";
      packageName = "restore-cursor";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/restore-cursor/-/restore-cursor-3.1.0.tgz";
        sha512 = "l+sSefzHpj5qimhFSE5a8nufZYAM3sBSVMAPtYkmC+4EH2anSGaEMXSD0izRQbu9nfyQ9y5JrVmp7E8oZrUjvA==";
      };
    };
    "resumer-0.0.0" = {
      name = "resumer";
      packageName = "resumer";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resumer/-/resumer-0.0.0.tgz";
        sha1 = "f1e8f461e4064ba39e82af3cdc2a8c893d076759";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==";
      };
    };
    "semaphore-async-await-1.5.1" = {
      name = "semaphore-async-await";
      packageName = "semaphore-async-await";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semaphore-async-await/-/semaphore-async-await-1.5.1.tgz";
        sha1 = "857bef5e3644601ca4b9570b87e9df5ca12974fa";
      };
    };
    "semver-6.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.0.tgz";
        sha512 = "b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==";
      };
    };
    "semver-7.3.4" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.4.tgz";
        sha512 = "tCfb2WLjqFAtXn4KEdxIhalnRtoKFN7nAwj0B3ZXCbQloV2tq5eDbcTmT68JJD3nRJq24/XgxtQKFIpQdtvmVw==";
      };
    };
    "seq-0.3.5" = {
      name = "seq";
      packageName = "seq";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/seq/-/seq-0.3.5.tgz";
        sha1 = "ae02af3a424793d8ccbf212d69174e0c54dffe38";
      };
    };
    "set-blocking-2.0.0" = {
      name = "set-blocking";
      packageName = "set-blocking";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz";
        sha1 = "045f9782d011ae9a6803ddd382b24392b3d890f7";
      };
    };
    "signal-exit-3.0.3" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.3.tgz";
        sha512 = "VUJ49FC8U1OxwZLxIbTTrDvLnf/6TDgxZcK8wxR8zs13xpx7xbG60ndBlhNrFi2EMuFRoeDoJO7wthSLq42EjA==";
      };
    };
    "source-map-0.1.43" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.1.43";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.1.43.tgz";
        sha1 = "c24bc146ca517c1471f5dacbe2571b2b7f9e3346";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-0.7.3" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.7.3.tgz";
        sha512 = "CkCj6giN3S+n9qrYiBTX5gystlENnRW5jZeNLHpe6aue+SrHcG5VYwujhW9s4dY31mEGsxBDrHR6oI69fTXsaQ==";
      };
    };
    "source-map-resolve-0.5.3" = {
      name = "source-map-resolve";
      packageName = "source-map-resolve";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-resolve/-/source-map-resolve-0.5.3.tgz";
        sha512 = "Htz+RnsXWk5+P2slx5Jh3Q66vhQj1Cllm0zvnaY98+NFx+Dv2CF/f5O/t8x+KaNdrdIAsruNzoh/KpialbqAnw==";
      };
    };
    "source-map-url-0.4.1" = {
      name = "source-map-url";
      packageName = "source-map-url";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-url/-/source-map-url-0.4.1.tgz";
        sha512 = "cPiFOTLUKvJFIg4SKVScy4ilPPW6rFgMgfuZJPNoDuMs3nC1HbMUycBoJw77xFIp6z1UJQJOfx6C9GMH80DiTw==";
      };
    };
    "spiro-2.0.0" = {
      name = "spiro";
      packageName = "spiro";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spiro/-/spiro-2.0.0.tgz";
        sha512 = "KPWXN+OmQdjZPCMGRkE2hsbcY4Y4UJxjn+qTw4rsJ49n8VN6EqPk0UOOkNihXEl3JEqPQxcrDQebu9YPn9Ad4w==";
      };
    };
    "split-1.0.1" = {
      name = "split";
      packageName = "split";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/split/-/split-1.0.1.tgz";
        sha512 = "mTyOoPbrivtXnwnIxZRFYRrPNtEFKlpB2fvjSnCQUiAA6qAZzqwna5envK4uk6OIeP17CsdF3rSBGYVBsU0Tkg==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "stack-trace-0.0.9" = {
      name = "stack-trace";
      packageName = "stack-trace";
      version = "0.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.9.tgz";
        sha1 = "a8f6eaeca90674c333e7c43953f275b451510695";
      };
    };
    "string-width-4.2.0" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.0.tgz";
        sha512 = "zUz5JD+tgqtuDjMhwIg5uFVV3dtqZ9yQJlZVfq4I01/K5Paj5UHj7VyrQOJvzawSVlKpObApbfD0Ed6yJc+1eg==";
      };
    };
    "strip-ansi-6.0.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.0.tgz";
        sha512 = "AuvKTrTfQNYNIctbR1K/YGTR1756GycPsg7b9bdV9Duqur4gv6aKqHXah67Z8ImS7WEz5QVcOtlfW2rZEugt6w==";
      };
    };
    "stylus-0.54.8" = {
      name = "stylus";
      packageName = "stylus";
      version = "0.54.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylus/-/stylus-0.54.8.tgz";
        sha512 = "vr54Or4BZ7pJafo2mpf0ZcwA74rpuYCZbxrHBsH8kbcXOwSfvBFwsRfpGO5OD5fhG5HDCFW737PKaawI7OqEAg==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "toposort-2.0.2" = {
      name = "toposort";
      packageName = "toposort";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/toposort/-/toposort-2.0.2.tgz";
        sha1 = "ae21768175d1559d48bef35420b2f4962f09c330";
      };
    };
    "traverse-0.3.9" = {
      name = "traverse";
      packageName = "traverse";
      version = "0.3.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/traverse/-/traverse-0.3.9.tgz";
        sha1 = "717b8f220cc0bb7b44e40514c22b2e8bbc70d8b9";
      };
    };
    "ts-process-promises-1.0.2" = {
      name = "ts-process-promises";
      packageName = "ts-process-promises";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ts-process-promises/-/ts-process-promises-1.0.2.tgz";
        sha512 = "6qWWz2HdFbD2uAfgS5t65Dd6HQKYjfra+YXQzKzxIG+RKTpoeDi+x+TW85SEF3cWUI2UecrOXJobvD+04MiTZg==";
      };
    };
    "tslib-1.14.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-1.14.1.tgz";
        sha512 = "Xni35NKzjgMrwevysHTCArtLDpPvye8zV/0E4EyYn43P7/7qvQwPh9BGkHewbMulVntbigmcT7rdX3BNo9wRJg==";
      };
    };
    "tslib-2.1.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.1.0.tgz";
        sha512 = "hcVC3wYEziELGGmEEXue7D75zbwIIVUMWAVbHItGPx0ziyXxrOMQx4rQEVEV45Ut/1IotuEvwqPopzIOkDMf0A==";
      };
    };
    "type-check-0.3.2" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.3.2.tgz";
        sha1 = "5884cab512cf1d355e3fb784f30804b2b520db72";
      };
    };
    "typo-geom-0.11.1" = {
      name = "typo-geom";
      packageName = "typo-geom";
      version = "0.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/typo-geom/-/typo-geom-0.11.1.tgz";
        sha512 = "DqAx/eGYLJprgRHEV2cMQBzRJo2N9UdBJ2eN54OeZ9chHbq+9U059lLY2DUxeGMff5rtTyG966CuL9aO4csxbQ==";
      };
    };
    "unicoderegexp-0.4.1" = {
      name = "unicoderegexp";
      packageName = "unicoderegexp";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unicoderegexp/-/unicoderegexp-0.4.1.tgz";
        sha1 = "afb10e4ef1eeddc711417bbb652bc885da9d4171";
      };
    };
    "universalify-2.0.0" = {
      name = "universalify";
      packageName = "universalify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-2.0.0.tgz";
        sha512 = "hAZsKq7Yy11Zu1DE0OzWjw7nnLZmJZYTDZZyEFHZdUhV8FkH5MCfoU1XMaxXovpyW5nq5scPqq0ZDP9Zyl04oQ==";
      };
    };
    "urix-0.1.0" = {
      name = "urix";
      packageName = "urix";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/urix/-/urix-0.1.0.tgz";
        sha1 = "da937f7a62e21fec1fd18d49b35c2935067a6c72";
      };
    };
    "verda-1.2.1" = {
      name = "verda";
      packageName = "verda";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/verda/-/verda-1.2.1.tgz";
        sha512 = "hEkyReHbrar3MikWeZTLWaR3Sr7KAl/M+KczKgGs80LHTPaKC06ussYuWVg9lMeOrwbOZb1o3DRNv91VzoGoYg==";
      };
    };
    "wawoff2-1.0.2" = {
      name = "wawoff2";
      packageName = "wawoff2";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wawoff2/-/wawoff2-1.0.2.tgz";
        sha512 = "qxuTwf5tAP/XojrRc6cmR0hGvqgD3XUxv2fzfzURKPDfE7AeHmtRuankVxdJ4DRdSKXaE5QlyJT49yBis2vb6Q==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "which-module-2.0.0" = {
      name = "which-module";
      packageName = "which-module";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-module/-/which-module-2.0.0.tgz";
        sha1 = "d9ef07dce77b9902b8a3a8fa4b31c3e3f7e6e87a";
      };
    };
    "word-wrap-1.2.3" = {
      name = "word-wrap";
      packageName = "word-wrap";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/word-wrap/-/word-wrap-1.2.3.tgz";
        sha512 = "Hz/mrNwitNRh/HUAtM/VT/5VH+ygD6DV7mYKZAtHOrbs8U7lvPS6xf7EJKMF0uW1KJCl0H701g3ZGus+muE5vQ==";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
    "wrap-ansi-6.2.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-6.2.0.tgz";
        sha512 = "r6lPcBGxZXlIcymEu7InxDMhdW0KDxpLgoFLcguasxCaJ/SOIZwINatK9KY/tf+ZrlywOKU0UDj3ATXUBfxJXA==";
      };
    };
    "wrap-ansi-7.0.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz";
        sha512 = "YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "xmldom-0.4.0" = {
      name = "xmldom";
      packageName = "xmldom";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmldom/-/xmldom-0.4.0.tgz";
        sha512 = "2E93k08T30Ugs+34HBSTQLVtpi6mCddaY8uO+pMNk1pqSjV5vElzn4mmh6KLxN3hki8rNcHSYzILoh3TEWORvA==";
      };
    };
    "xpath-0.0.32" = {
      name = "xpath";
      packageName = "xpath";
      version = "0.0.32";
      src = fetchurl {
        url = "https://registry.npmjs.org/xpath/-/xpath-0.0.32.tgz";
        sha512 = "rxMJhSIoiO8vXcWvSifKqhvV96GjiD5wYb8/QHdoRyQvraTpp4IEv944nhGausZZ3u7dhQXteZuZbaqfpB7uYw==";
      };
    };
    "y18n-4.0.1" = {
      name = "y18n";
      packageName = "y18n";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/y18n/-/y18n-4.0.1.tgz";
        sha512 = "wNcy4NvjMYL8gogWWYAO7ZFWFfHcbdbE57tZO8e4cbpj8tfUcwrwqSl3ad8HxpYWCdXcJUCeKKZS62Av1affwQ==";
      };
    };
    "y18n-5.0.5" = {
      name = "y18n";
      packageName = "y18n";
      version = "5.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/y18n/-/y18n-5.0.5.tgz";
        sha512 = "hsRUr4FFrvhhRH12wOdfs38Gy7k2FFzB9qgN9v3aLykRq0dRcdcpz5C9FxdS2NuhOrI/628b/KSTJ3rwHysYSg==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "yargs-15.4.1" = {
      name = "yargs";
      packageName = "yargs";
      version = "15.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-15.4.1.tgz";
        sha512 = "aePbxDmcYW++PaqBsJ+HYUFwCdv4LVvdnhBy78E57PIor8/OVvhMrADFFEDh8DHDFRv/O9i3lPhsENjO7QX0+A==";
      };
    };
    "yargs-16.2.0" = {
      name = "yargs";
      packageName = "yargs";
      version = "16.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-16.2.0.tgz";
        sha512 = "D1mvvtDG0L5ft/jGWkLpG1+m0eQxOfaBvTNELraWj22wSVUMWxZUvYgJYcKh6jGGIkJFhH4IZPQhR4TKpc8mBw==";
      };
    };
    "yargs-parser-18.1.3" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "18.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-18.1.3.tgz";
        sha512 = "o50j0JeToy/4K6OZcaQmW6lyXXKhq7csREXcDwk2omFPJEwUNOVtJKvmDr9EI1fAJZUyZcRF7kxGBWmRXudrCQ==";
      };
    };
    "yargs-parser-20.2.4" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "20.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-20.2.4.tgz";
        sha512 = "WOkpgNhPTlE73h4VFAFsOnomJVaovO8VqLDzy5saChRBFQFBoMYirowyW+Q9HB4HFF4Z7VZTiG3iSzJJA29yRA==";
      };
    };
  };
  args = {
    name = "iosevka";
    packageName = "iosevka";
    version = "5.0.0-rc.1";
    src = ./.;
    dependencies = [
      sources."@iarna/toml-2.2.5"
      sources."@ot-builder/bin-composite-types-1.0.1"
      sources."@ot-builder/bin-util-1.0.1"
      (sources."@ot-builder/cli-help-shower-1.0.1" // {
        dependencies = [
          sources."ansi-styles-4.3.0"
          sources."chalk-4.1.0"
          sources."color-convert-2.0.1"
          sources."color-name-1.1.4"
          sources."has-flag-4.0.0"
          sources."supports-color-7.2.0"
        ];
      })
      (sources."@ot-builder/cli-proc-1.0.1" // {
        dependencies = [
          sources."ansi-styles-4.3.0"
          sources."chalk-4.1.0"
          sources."color-convert-2.0.1"
          sources."color-name-1.1.4"
          sources."has-flag-4.0.0"
          sources."supports-color-7.2.0"
        ];
      })
      (sources."@ot-builder/cli-shared-1.0.1" // {
        dependencies = [
          sources."ansi-styles-4.3.0"
          sources."chalk-4.1.0"
          sources."color-convert-2.0.1"
          sources."color-name-1.1.4"
          sources."has-flag-4.0.0"
          sources."supports-color-7.2.0"
        ];
      })
      sources."@ot-builder/common-impl-1.0.1"
      sources."@ot-builder/errors-1.0.1"
      sources."@ot-builder/io-bin-cff-1.0.1"
      sources."@ot-builder/io-bin-encoding-1.0.1"
      sources."@ot-builder/io-bin-ext-private-1.0.1"
      sources."@ot-builder/io-bin-font-1.0.1"
      sources."@ot-builder/io-bin-glyph-store-1.0.1"
      sources."@ot-builder/io-bin-layout-1.0.1"
      sources."@ot-builder/io-bin-metadata-1.0.1"
      sources."@ot-builder/io-bin-metric-1.0.1"
      sources."@ot-builder/io-bin-name-1.0.1"
      sources."@ot-builder/io-bin-sfnt-1.0.1"
      sources."@ot-builder/io-bin-ttf-1.0.1"
      sources."@ot-builder/ot-1.0.1"
      sources."@ot-builder/ot-encoding-1.0.1"
      sources."@ot-builder/ot-ext-private-1.0.1"
      sources."@ot-builder/ot-glyphs-1.0.1"
      sources."@ot-builder/ot-layout-1.0.1"
      sources."@ot-builder/ot-metadata-1.0.1"
      sources."@ot-builder/ot-name-1.0.1"
      sources."@ot-builder/ot-sfnt-1.0.1"
      sources."@ot-builder/ot-standard-glyph-namer-1.0.1"
      sources."@ot-builder/prelude-1.0.1"
      sources."@ot-builder/primitive-1.0.1"
      sources."@ot-builder/rectify-1.0.1"
      sources."@ot-builder/stat-glyphs-1.0.1"
      sources."@ot-builder/trace-1.0.1"
      sources."@ot-builder/var-store-1.0.1"
      sources."@ot-builder/variance-1.0.1"
      sources."@unicode/unicode-13.0.0-1.0.3"
      sources."amdefine-1.0.1"
      sources."ansi-regex-5.0.0"
      sources."ansi-styles-3.2.1"
      sources."argparse-1.0.10"
      sources."async-0.9.2"
      sources."at-least-node-1.0.0"
      sources."atob-2.1.2"
      sources."balanced-match-1.0.0"
      sources."bluebird-3.7.2"
      sources."brace-expansion-1.1.11"
      sources."camelcase-5.3.1"
      sources."chainsaw-0.0.9"
      sources."chalk-2.4.2"
      sources."cldr-5.8.0"
      sources."cli-cursor-3.1.0"
      sources."clipper-lib-6.4.2"
      sources."cliui-7.0.4"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."concat-map-0.0.1"
      sources."css-2.2.4"
      sources."css-parse-2.0.0"
      sources."debug-3.1.0"
      sources."decamelize-1.2.0"
      sources."decode-uri-component-0.2.0"
      sources."deep-is-0.1.3"
      sources."ejs-3.1.6"
      sources."emoji-regex-8.0.0"
      sources."escalade-3.1.1"
      sources."escape-string-regexp-1.0.5"
      sources."escodegen-2.0.0"
      (sources."escope-1.0.3" // {
        dependencies = [
          sources."estraverse-2.0.0"
        ];
      })
      (sources."esmangle-1.0.1" // {
        dependencies = [
          sources."escodegen-1.3.3"
          sources."esprima-1.1.1"
          sources."estraverse-1.5.1"
          sources."esutils-1.0.0"
          sources."fast-levenshtein-1.0.7"
          sources."levn-0.2.5"
          sources."optionator-0.3.0"
          sources."source-map-0.1.43"
        ];
      })
      sources."esprima-4.0.1"
      (sources."esshorten-1.1.1" // {
        dependencies = [
          sources."estraverse-4.1.1"
        ];
      })
      sources."estraverse-5.2.0"
      sources."esutils-2.0.3"
      sources."fast-deep-equal-3.1.3"
      sources."fast-levenshtein-2.0.6"
      sources."filelist-1.0.2"
      sources."find-up-4.1.0"
      sources."fs-extra-9.1.0"
      sources."fs.realpath-1.0.0"
      sources."function-bind-1.1.1"
      sources."get-caller-file-2.0.5"
      sources."glob-7.1.6"
      sources."graceful-fs-4.2.5"
      sources."has-1.0.3"
      sources."has-flag-3.0.0"
      sources."hashish-0.0.4"
      sources."iconv-lite-0.6.2"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."is-core-module-2.2.0"
      sources."is-fullwidth-code-point-3.0.0"
      sources."isexe-2.0.0"
      sources."jake-10.8.2"
      sources."jsonfile-6.1.0"
      sources."levn-0.3.0"
      sources."locate-path-5.0.0"
      sources."lru-cache-2.5.0"
      sources."memoizeasync-1.1.0"
      sources."mimic-fn-2.1.0"
      sources."minimatch-3.0.4"
      sources."mkdirp-1.0.4"
      sources."ms-2.0.0"
      sources."once-1.4.0"
      sources."onetime-5.1.2"
      sources."optionator-0.8.3"
      sources."ot-builder-1.0.1"
      (sources."otb-ttc-bundle-1.0.1" // {
        dependencies = [
          sources."ansi-styles-4.3.0"
          sources."chalk-4.1.0"
          sources."color-convert-2.0.1"
          sources."color-name-1.1.4"
          sources."has-flag-4.0.0"
          sources."supports-color-7.2.0"
        ];
      })
      sources."p-limit-2.3.0"
      sources."p-locate-4.1.0"
      sources."p-try-2.2.0"
      sources."passerror-1.1.1"
      sources."patel-0.34.0"
      sources."path-exists-4.0.0"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.6"
      sources."patrisika-0.22.2"
      sources."patrisika-scopes-0.11.1"
      sources."pegjs-0.10.0"
      sources."prelude-ls-1.1.2"
      sources."require-directory-2.1.1"
      sources."require-main-filename-2.0.0"
      sources."resolve-1.19.0"
      sources."resolve-url-0.2.1"
      sources."restore-cursor-3.1.0"
      sources."resumer-0.0.0"
      sources."safer-buffer-2.1.2"
      sources."sax-1.2.4"
      sources."semaphore-async-await-1.5.1"
      (sources."semver-7.3.4" // {
        dependencies = [
          sources."lru-cache-6.0.0"
        ];
      })
      sources."seq-0.3.5"
      sources."set-blocking-2.0.0"
      sources."signal-exit-3.0.3"
      sources."source-map-0.6.1"
      sources."source-map-resolve-0.5.3"
      sources."source-map-url-0.4.1"
      (sources."spiro-2.0.0" // {
        dependencies = [
          sources."tslib-1.14.1"
        ];
      })
      sources."split-1.0.1"
      sources."sprintf-js-1.0.3"
      sources."stack-trace-0.0.9"
      sources."string-width-4.2.0"
      sources."strip-ansi-6.0.0"
      (sources."stylus-0.54.8" // {
        dependencies = [
          sources."semver-6.3.0"
          sources."source-map-0.7.3"
        ];
      })
      sources."supports-color-5.5.0"
      sources."through-2.3.8"
      sources."toposort-2.0.2"
      sources."traverse-0.3.9"
      sources."ts-process-promises-1.0.2"
      sources."tslib-2.1.0"
      sources."type-check-0.3.2"
      sources."typo-geom-0.11.1"
      sources."unicoderegexp-0.4.1"
      sources."universalify-2.0.0"
      sources."urix-0.1.0"
      (sources."verda-1.2.1" // {
        dependencies = [
          sources."ansi-styles-4.3.0"
          sources."chalk-4.1.0"
          sources."cliui-6.0.0"
          sources."color-convert-2.0.1"
          sources."color-name-1.1.4"
          sources."has-flag-4.0.0"
          sources."supports-color-7.2.0"
          sources."wrap-ansi-6.2.0"
          sources."y18n-4.0.1"
          sources."yargs-15.4.1"
          sources."yargs-parser-18.1.3"
        ];
      })
      sources."wawoff2-1.0.2"
      sources."which-2.0.2"
      sources."which-module-2.0.0"
      sources."word-wrap-1.2.3"
      sources."wordwrap-0.0.3"
      (sources."wrap-ansi-7.0.0" // {
        dependencies = [
          sources."ansi-styles-4.3.0"
          sources."color-convert-2.0.1"
          sources."color-name-1.1.4"
        ];
      })
      sources."wrappy-1.0.2"
      sources."xmldom-0.4.0"
      sources."xpath-0.0.32"
      sources."y18n-5.0.5"
      sources."yallist-4.0.0"
      sources."yargs-16.2.0"
      sources."yargs-parser-20.2.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
