#!/bin/bash
echo -e "              \e[32m&&"
echo -e "             \e[32m&&&&&"
echo -e "           \e[32m&&&\/& &&&"
echo -e "          \e[32m&&\e[33m|,/  |/\e[32m& &&"
echo -e "           \e[32m&&\e[33m/   /  /_\e[32m&  &&"
echo -e "             \e[33m\  {  |_____/_\e[32m&"
echo -e "             \e[33m{  / /          \e[32m&&&"
echo -e "             \e[33m.\`. \\{___\________\/_\}"
echo -e "              \e[33m\} \}\{       \\"
echo -e "              \e[33m}\{\{         \\____\e[32m&"
echo -e "             \e[33m\{\}\{           \`\e[32m&\e[33m\\e[32m&&"
echo -e "             \e[33m{{}             \e[32m&&"
echo -e "       \e[33m, -=-~{ .-^- _"
echo -e "             \`}"
echo -e "              {"
