#!/bin/sh -eu
# Slightly modifed, original by
#    Drew DeVault: https://git.sr.ht/~sircmpwn/dotfiles/tree/master/bin/paste
. ~/.config/sr.ht
PASTESRHT=${PASTESRHT:-https://paste.sr.ht}
fname=$(bemenu -np 'File name: ' </dev/null)

if [ "$fname" == "exit" ]; then
	exit 1
fi

result=$(wl-paste | jq -sR '{
	"files": [
		{
			"contents": .,
			"filename": "'"$fname"'",
		}
	],
	"visibility": "unlisted"
}' | curl \
	-H Authorization:"token $oauth_token" \
	-H Content-Type:application/json \
	-X POST \
	-d @- $PASTESRHT/api/pastes)

printf '%s\n' "$result"
sha=$(printf '%s' "$result" | jq -r .sha)
user=$(printf '%s' "$result" | jq -r .user.canonical_name)
xdg-open "$PASTESRHT/$user/$sha"
wl-copy "$PASTESRHT/$user/$sha"
echo "$PASTESRHT/$user/$sha" >> ~/pastesrht
