[fsmonitor]
# backend = "watchman"
# watchman.register-snapshot-trigger = true

[user]
name = "Cole Helbling"
email = "cole.e.helbling@outlook.com"

[ui]
pager = "less -FRX"
default-command = ["log", "-r", "stack()"]
diff-editor = ":builtin"
bookmark-list-sort-keys = ["committer-date-", "author-date-", "name"]
# show-cryptographic-signatures = true

[signing]
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINMcTaqUZSwv6YW8lx/JhsAZTdNSSC2fR8Pgk8woeFKh"
behavior = "drop" # don't sign commits until push (see git.sign-on-push)
# backends.ssh.allowed-signers = "~/.config/jj/allowed-signers"

[git]
sign-on-push = true
write-change-id-header = true
fetch = "glob:*"
private-commits = "denylist()"

[templates]
git_push_bookmark = '"cole-h/push-" ++ change_id.short()'

[revset-aliases]
'T' = 'trunk()'
# Useful for abandoning branches off of trunk that are making the jj log too long
'abm(r)' = '::fork_point(r) & mutable()'
# The default log revset, so it can be referred to in the short-prefixes revset below
# https://github.com/jj-vcs/jj/blob/bb3b61d7e17a3df09baa07bad3c565fb177ab696/cli/src/config/revsets.toml#L10C8-L10C73
'log()' = "present(@) | ancestors(immutable_heads().., 2) | present(trunk())"

'user(x)' = 'author(x) | committer(x)'
'mine()' = '''
user("cole.e.helbling@outlook.com")
| user("cole.helbling@determinate.systems")
'''

# 'immutable_heads()' = 'builtin_immutable_heads() | (trunk().. & ~mine())'

[aliases]
n = ["new", "-A"]
jj = []
drop = ["abandon", "--retain-bookmarks"]

[revsets]
log-graph-prioritize = 'coalesce(merges(), trunk())'
short-prefixes = "log() ~ (@ & description(exact:''))"
