[fsmonitor]
# backend = "watchman"
# watchman.register-snapshot-trigger = true

[user]
name = "Cole Helbling"
email = "cole.e.helbling@outlook.com"

[ui]
pager = "less -FRX"
default-command = ["log", "-r", "stack()"]
diff-editor = ":builtin"
graph.style = "square"
bookmark-list-sort-keys = ["committer-date-", "author-date-", "name"]
# show-cryptographic-signatures = true

[signing]
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINMcTaqUZSwv6YW8lx/JhsAZTdNSSC2fR8Pgk8woeFKh"
behavior = "drop" # don't sign commits until push (see git.sign-on-push)
# backends.ssh.allowed-signers = "~/.config/jj/allowed-signers"

[git]
sign-on-push = true
write-change-id-header = true
fetch = "glob:*"

[templates]
git_push_bookmark = '"cole-h/push-" ++ change_id.short()'

[revset-aliases]
'T' = 'trunk()'
# Useful for abandoning branches off of trunk that are making the jj log too long
'abm(r)' = '::fork_point(r) & mutable()'

# 'immutable_heads()' = 'builtin_immutable_heads() | (trunk().. & ~mine())'

[aliases]
n = ["new"]
jj = []
