# https://github.com/jj-vcs/jj/discussions/5568#discussioncomment-12674748
[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_pushable(to)' = 'heads(::to & ~description(exact:"") & (~empty() | merges()))'

[aliases]
hop = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "closest_pushable(@)"]

nudge = ["util", "exec", "--", "sh", "-c", """
set -e
jj hop
jj git push
""", ""]
