# https://github.com/jj-vcs/jj/discussions/5568#discussioncomment-12674748
[revset-aliases]
'closest_untracked_bookmarks(to)' = 'heads(::to & remote_bookmarks() ~ bookmarks())'
'closest_bookmarks(to)' = 'heads(::to & bookmarks() ~ trunk())'
'closest_pushables(to)' = 'heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()) ~ denylist())'

'closest_untracked_bookmark(to)' = 'exactly(closest_untracked_bookmarks(to), 1)'
'closest_bookmark(to)' = 'exactly(closest_bookmarks(to), 1)'
'closest_pushable(to)' = 'exactly(closest_pushables(to), 1)'

[aliases]
hop = ["util", "exec", "--", "sh", "-c", """
if [ "x$1" = "x" ]; then
  jj bookmark move --from "closest_bookmark(@)" --to "closest_pushable(@)"
else
  jj bookmark move --to "closest_pushable(@)" "$@"
fi
""", "jj-hop"]

nudge = ["util", "exec", "--", "sh", "-c", """
set -e
jj hop
jj git push "$@"
""", "jj-nudge"]


# https://andre.arko.net/2025/09/28/stupid-jj-tricks/
pr = ["util", "exec", "--", "bash", "-c", """
gh pr create --head "$(jj log -r 'closest_bookmark(@)' -T 'bookmarks' --no-graph)"
""", "jj-pr"]
