[revset-aliases]
# https://github.com/thoughtpolice/a/blob/f1a88bacc4e9a3ec0d6913caf3c32f042226dc10/tilde/aseipp/dotfiles/jj/config.toml

# stack(x, n) is the set of mutable commits reachable from 'x', with 'n'
# parents. 'n' is often useful to customize the display and return set for
# certain operations. 'x' can be used to target the set of 'roots' to traverse,
# e.g. @ is the current stack.
'stack()' = 'stack(@)'
'stack(x)' = 'stack(x, 2)'
'stack(x, n)' = 'ancestors(reachable(x, mutable()), n)'

# The current set of "open" works. It is defined as: all stacks that are
# reachable from my working copy, or any other commit I wrote.
# n = 1, meaning that nothing from `trunk()` is included, so all resulting
# commits are mutable by definition.
'open()' = 'stack(mine() | @, 1)'

# Private and WIP commits that should never be pushed anywhere. Often part of
# work-in-progress merge stacks.
# 'wip()' = 'description(glob-i:"wip:*") | description(glob-i:"[[]WIP[]]*")'
'wip()' = 'none()'
'private()' = 'description(glob-i:"private:*") | description(glob-i:"[[]PRIVATE[]]*")'
'denylist()' = '''
wip() | (descendants(wip()) ~ descendants(merges() ~ ancestors(trunk())))
| private() | (descendants(private()) ~ descendants(merges() ~ ancestors(trunk())))
'''

# Find the megamerge. Mostly useful in combination with other aliases, primarily
# 'sandwich'. Normally when there's only one megamerge, sandwich works perfectly
# fine and is basically "magic". However, there are more complex cases; consider
# something like this which represents a forked repository of an upstream:
#
#
#    ----> P1 ... Pn -----------\
#   /                            \
#  /---> X --\           (main)   \
# B          M1 --> T1 ... Tn --> M2 --> @
#  \---> Y --/
#
# X and Y are typical features on top of base B, combined inside megamerge M1.
# However, we may want changes T1...Tn to go on top of M1, because (in my case)
# they're custom and will never go upstream, but are correctly published as part
# of the fork; Tn is where the main bookmark points. Finally, we have changes P1
# ... Pn which are private and should never be pushed upstream at all.
#
# In this case, sandwich will work poorly because 'reachable(stack(), merges())'
# will resolve to {M1, M2}, which is not what we want for 'rebase -B'. So to
# handle that case, we allow the user to specify the merge via literal tag
# "megamerge". In this case if we 'bookmark set megamerge -r M1' then sandwich
# will always work correctly.
'megamerge()' = '''coalesce(
  present(megamerge),
  reachable(stack(), merges())
)
'''

# https://github.com/jj-vcs/jj/discussions/5669#discussioncomment-12178856
'why_immutable(r)' = '(r & immutable()) | roots(r:: & immutable_heads())'

# WIP: try to get the commit immediately after forking off of trunk()
# useful when trying to squash an entire branch with `jj squash --from 'base(x)+::' --into 'base(x)'` and just put in any change on that branch as x
'base(x)' = 'fork_point(trunk()..x)+ & ::x'

[aliases]
# https://gist.github.com/thoughtpolice/8f2fd36ae17cd11b8e7bd93a70e31ad6/
# Retrunk a series. Typically used as `jj retrunk -s ...`, and notably can be
# used with open:
# - jj retrunk -s 'all:roots(open())'
retrunk = ["rebase", "-d", "trunk()"]

retrunk-all = ["retrunk", "-s", "all:roots(open())"]

# Retrunk the current stack of work.
reheat = ["rebase", "-d", "trunk()", "-s", "all:roots(trunk()..stack(@))"]

renew = ["util", "exec", "--", "sh", "-c", """
set -eu

new_base="${1:-trunk()}"

jj git fetch
jj new ${new_base}
""", "jj-renew"]

gcl = ["git", "clone", "--colocate"]
